### ISSUE TITLE
MilkMaid.find(actor) not working properly

### ISSUE THREAD

**Issue by ghost** [ak86/Milk-Mod-Economy#17]
I'm having trouble with the MilkMaid.find(actor) and MilkSlave.find(actor) function.
How to reproduce:
- Player character is not a milk maid
- Follower is a milk maid (confirmed via MCM menu)
- point crosshair at NPC
- press '9' (notification key)

The notification always says: ""Target is not a milk maid/slave." If the player character is a milk maid, then it will show the player's statistics instead. I added some logging messages and both MilkMaid.find(actor) and MilkSlave.find(actor) definitely return '-1'. (I also made sure to be close to the NPC to avoid any chance of Skyrim thinking there's something else in between or the target being too far away.)

I tried a couple of different git commits and also v2016-03-27 (each time with and without follower being already a milkmaid), but the behaviour is always the same. Can you confirm this behaviour?

_I also checked the git log and the function 'OnKeyDown' hasn't changed at all since the first commit. Either this is broken for quite some time now or something is wrong with my installation._

**Comment by ak86** [comment]
yes i didnt add     RegisterForCrosshairRef() to VarSetup() when i made default 9 hotkey
can fix that with setting hotkey in mcm
