### ISSUE TITLE
property MilkE was removed from .psc but not from .esp

### ISSUE THREAD

**Issue by ghost** [ak86/Milk-Mod-Economy#21]
The property 'MilkE' was removed from MilkMCM.psc but is still present in MilkModNew.esp:

![image](https://cloud.githubusercontent.com/assets/915497/17524852/87136b6c-5e60-11e6-9c1c-02f8cea58e33.png)

It now causes load errors:
`warning: Property MilkE on script MilkMCM attached to MME_MilkQUEST (0C00E209) cannot be initialized because the script no longer contains that property`

The property was removed in commit 88b3e21a0cb0ab563d7000f8348cf1b0ad8eba50. Please also remove it from the plugin file.

**Comment by ak86** [comment]
i know, ive only edited scripts, will do esp after finish with scripts
and mcm needs fixing too

**Comment by ak86** [comment]
or not

**Comment by ak86** [comment]
check
