### ISSUE TITLE
MilkQuest.psc: suspicious code in lines 1392-1395

### ISSUE THREAD

**Issue by ghost** [ak86/Milk-Mod-Economy#5]
What is the purpose of lines 1392-1395 in MilkQuest.psc?

```
if IsMilkMaid == true
  PainCnt = StorageUtil.GetFloatValue(akActor,"MME.MilkMaid.PainCount", missing = 0)
  StorageUtil.SetFloatValue(akActor,"MME.MilkMaid.PainCount", PainCnt)
endif
```

I think either the GetFloatValue or the SetFloatValue is superfluous and should be deleted.
- Deleting GetFloatValue would make the code similar to the conditional in 1379-1388.
- Or maybe the Get is supposed to reset the current value of PainCount to whatever it was before. (But then it begs the question why bother about immediately setting it again?)

Or maybe something else is going on and this is indeed as intended. If this is the case then please add a comment to explain it.

**Comment by ak86** [comment]
hm... its a leftover of merging of 2 functions year ago
