### ISSUE TITLE
Bug: Milkmaid initialization is triggered twice

### ISSUE THREAD

**Issue by ghost** [ak86/Milk-Mod-Economy#7]
Confirmed for player character using milking machine
(using commit f103840f28614bebd04a3157fcb5fd739936c1b7 with recompiled scripts)
- use a non-Milkmaid player character
- enter milking machine
- (initialization triggers)
- decline 'become milkmaid' dialogue
- (character is fed lactacid and milked)
- exit milking machine
  Result: Player character is listed as a milkmaid in MCM-MME menu.

(If the 'become milkmaid' dialogue is confirmed the character is initialized a second time.)

**Comment by ak86** [comment]
caused by slsw,
fixd
